### ISSUE TITLE
Principle of operation

### ISSUE THREAD

**Issue by andrey-belokon** [profdc9/VNA#2]
Hi,
As I can see you implemented magnitude/phase measurement without sin/cos multiplication which used in EU1KY analyzer. Can you describe principle of operation for used method or give me URL if this information found somewhere in web. Thanks
73! Andrew

**Comment by profdc9** [comment]
The signal is recorded at 4 times its frequency.  The LM339 comparator provides a clock so this can be done accurately.  So for example for a 10 kHz intermediate frequency, you sample at 40 kHz.  Then each successive sample is multiplied by +1, +j, -1, -j, because these are the four phases, which is just addition/subtraction to the real or imaginary part.  So to measure the in phase/quadrature component, only integer arithmetic is required in this case.
